### ISSUE TITLE
Chef server 12 runs under 'opscode' user, not 'chef_server'

### ISSUE THREAD

**Issue by dwradcliffe** [opscode-cookbooks/chef-client#196]
This `dir_owner` helper will return 'chef_server' and thus the config recipe will fail every time.

```
Chef::Exceptions::UserIDNotFound: template[/etc/chef/client.rb] (chef-client::config line 73) had an error: Chef::Exceptions::UserIDNotFound: cannot determine user id for 'chef_server', does the user exist on this system?
```

https://github.com/opscode-cookbooks/chef-client/blob/bf1dbbc749c92315784b17bac796ed858a256f5d/recipes/config.rb#L70-L85

https://github.com/opscode-cookbooks/chef-client/blob/bf1dbbc749c92315784b17bac796ed858a256f5d/libraries/helpers.rb#L60-L66

https://github.com/opscode-cookbooks/chef-client/blob/bf1dbbc749c92315784b17bac796ed858a256f5d/libraries/helpers.rb#L26-L28

**Comment by gplessis** [comment]
Got bitten by this annoying issue today, after a Chef Server upgrade from 11 to 12. @jtimberman, @binamov, any update/status on this?

**Comment by joshskains** [comment]
Is there a solution to this? After a brutal upgrade from 11 to 12, we now have a chef-client break on our main chef server. That's really unacceptable. How did this get through QA?

**Comment by BarthV** [comment]
:+1: 
Didn't find out a workaround for this, pls make a move :)

**Comment by gplessis** [comment]
FYI using [chef-rewind](https://github.com/thommay/chef-rewind) is one possible temporary workaround to make `chef-client::config` converge on a system with Chef Server 12 installed.
```ruby
chef_gem "chef-rewind"
require 'chef/rewind'

include_recipe 'chef-client::config'
rewind :template => "#{node["chef_client"]["conf_dir"]}/client.rb" do
  owner 'root'
  group 'root'
end
```

**Comment by caquino** [comment]
Same issue here.

   * cannot determine user id for 'chef_server', does the user exist on this system?
    ================================================================================
    Error executing action `create` on resource 'template[/etc/chef/client.rb]'
    ================================================================================

    Chef::Exceptions::UserIDNotFound
    --------------------------------
    cannot determine user id for 'chef_server', does the user exist on this system?

**Comment by justindossey** [comment]
I worked around this with
```
include_recipe 'chef-client::config'
r = resources(template: '/etc/chef/client.rb')
r.user 'root'
r.group 'root'
```

**Comment by BackSlasher** [comment]
Created PR #259 in case the special case is really unnecessary, if @jtimberman decides there is no reason.

**Comment by ikurochkin** [comment]
I'm also having this problem.

**Comment by lebrinkma** [comment]
I also hit this bug today while trying to use the cookbook on a system with Chef Server 12 installed.

**Comment by Rockstar04** [comment]
This still seems to be an issue, #286 should fix this

Threw me for a loop, hope this get resolved soon
