### ISSUE TITLE
Windows Deploy gives Errno::EIO: Input/output error - CreateProcessW

### ISSUE THREAD

**Issue by blueo** [opscode-cookbooks/chef-client#198]
Using windows 8.1 to run chef to deploy git repo I get the error below when git is called:

`ErFATAL: Errno::EIO: deploy[C:\dir] (ts::default line 16) had an error: Errno::EIO: Input/output error - CreateProcessW`

I've checked to make sure git is on the path and I've replicated this on several 8.1 machines. I think the issue is that windows is expecting .exe/.bat/.cmd on the end of the git command.
The only way I've managed to get around it is use a custom provider [see this stackoverflow question](http://stackoverflow.com/questions/24631815/how-to-debug-errnoeio-error-in-chef-recipe-using-chefprovidergit).

The recipe is:
```
deploy "#{node['ts']['installdir']}" do
  repo 'https://myinternalrepo/repo.git'
  action :deploy
end
```
and the top of the stacktrace is:
```
Errno::EIO: deploy[C:\ts] (ts::default line 13) had an error: Errno::EIO: Input/output error - CreateProcessW
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0-x86-mingw32/lib/mixlib/shellout/windows/core_ext.rb:346:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0-x86-mingw32/lib/mixlib/shellout/windows.rb:86:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/mixlib-shellout-1.4.0-x86-mingw32/lib/mixlib/shellout.rb:227:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2-x86-mingw32/lib/chef/mixin/shell_out.rb:37:in `shell_out'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2-x86-mingw32/lib/chef/mixin/shell_out.rb:42:in `shell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2-x86-mingw32/lib/chef/provider/git.rb:250:in `remote_resolve_reference'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.2-x86-mingw32/lib/chef/provider/git.rb:229:in `target_revision'
```

any help debugging this further would be appreciated - I'm not sure if this a  problem with my setup or with chef...

**Comment by juliandunn** [comment]
Closing due to nonresponse.

**Comment by blueo** [comment]
Oops, completely forgot! Sorry you were right originally, its in the wrong place, apologies!
