### ISSUE TITLE
Update OS list for systemd

### ISSUE THREAD

**Issue by davidstrauss** [opscode-cookbooks/chef-client#218]
Add Fedora 21 to the systemd distribution list.

**Comment by juliandunn** [comment]
Which list is this you're referring to?

**Comment by davidstrauss** [comment]
There is a whitelist of distributions and releases that use systemd. Otherwise Chef assumes SysV init on Linux. Fedora 20 is on the current list, but Fedora 21 needs to be added.

**Comment by juliandunn** [comment]
Are you talking about the `init_style` logic inside this block? https://github.com/opscode-cookbooks/chef-client/blob/master/attributes/default.rb#L87 Or are you talking about what's in the config for test-kitchen?

**Comment by davidstrauss** [comment]
Looks like it actually got fixed six days ago:
https://github.com/opscode-cookbooks/chef-client/commit/6ebbe6320d10ece98abaf224808bc36e67a8301e

**Comment by juliandunn** [comment]
Roger that :grin:
