### ISSUE TITLE
chef-client doesn't setup itself as a service in os x 10.9

### ISSUE THREAD

**Issue by marcoamorales** [opscode-cookbooks/chef-client#245]
Hello,

Ran knife bootstrap on a os x 10.9 computer and chef-client didn't setup the launchd configuration to set itself up as a service.

Running Chef 12.0.3

Not sure what more info to give besides this. :frowning:

**Comment by jtimberman** [comment]
Did you use the default or service recipe from this cookbook?

**Comment by marcoamorales** [comment]
I didn't change any defaults, just ran knife bootstrap: `knife bootstrap <ip> -x user --sudo -r 'role[staging]'`

**Comment by jtimberman** [comment]
What is the run list of `role[staging]`?

**Comment by jtimberman** [comment]
Actually if you can just paste the entire role, that'd be cool too :smile_cat:.

**Comment by marcoamorales** [comment]
Here you go:
```
$ knife role show staging
chef_type:           role
default_attributes:
description:         
env_run_lists:
json_class:          Chef::Role
name:                staging
override_attributes:
run_list:
  recipe[homebrew]
  recipe[myorg-chef::monit-osx]
```

**Comment by jtimberman** [comment]
In `recipe[myorg-chef::monit-osx]` are you using `include_recipe "chef-client"` or `include_recipe "chef-client::service"`? 

Just running the `chef-client` doesn't set itself up as a service. You need to use a recipe to do that, and this cookbook provides such a recipe.

**Comment by marcoamorales** [comment]
I apologize, I wasn't including it properly. I fixed it, included the recipe `chef-client::service` and it sets itself up as a launchd service.

Thanks!
