### ISSUE TITLE
commit e510d8333687d861b784a30f01a2ea491ddb1c6b breaks logging

### ISSUE THREAD

**Issue by joshcoughlan** [opscode-cookbooks/chef-client#256]
Hello. There seems to be a problem with e510d8333687d861b784a30f01a2ea491ddb1c6b. When a chef-client runs (Centos 5, and probably 6) with this change in place it removes logging from the init scripts, but does not appear to update log_location in the client.rb. Suggestions?

**Comment by joshcoughlan** [comment]
Nevermind... I was calling the init_service recipe and not the default recipe

**Comment by joshcoughlan** [comment]
Update: even when calling the default recipe the logging is still broken. None of chef-client::{default,service,init_service} includes chef-client::config, thus the logging is disabled from the chef-client init.d script and sysconfig, but the logging behavior is never moved into the client.rb.

**Comment by juliandunn** [comment]
This is by design. If you want logging, use the `chef-client::config` recipe to set up the `client.rb` to do it. The responsibility of the service recipes is to manage Chef Client as a service.
