### ISSUE TITLE
Derived Attributes (Beyond the First) Non-Functional in Chef 12+

### ISSUE THREAD

**Issue by joshburt** [opscode-cookbooks/chef-client#258]
See: https://github.com/opscode-cookbooks/iis/issues/117

Validated that the 11.x Chef clients work fine, and the issue is present only in 12+ environments.  Using the IIS cookbook for example.

Within the cookbook attribute file: iis/attributes/default.rb

This is currently defined:
`default['iis']['home'] = "#{ENV['WINDIR']}\\System32\\inetsrv"`
`default['iis']['conf_dir'] = "#{iis['home']}\\config"`
`default['iis']['pubroot'] = "#{ENV['SYSTEMDRIVE']}\\inetpub"`
`default['iis']['docroot'] = "#{iis['pubroot']}\\wwwroot"`
`default['iis']['log_dir'] = "#{iis['pubroot']}\\logs\\LogFiles"`
`default['iis']['cache_dir'] = "#{iis['pubroot']}\\temp"`

As of chef 12 only the first derived attribute is properly calculated. Printing out the values within a run is enough to see the issue:
DEBUG: default['iis']['home'] = C:\Windows\System32\inetsrv
DEBUG: default['iis']['conf_dir'] = C:\Windows\System32\inetsrv\config
DEBUG: default['iis']['pubroot'] = C:\inetpub
DEBUG: default['iis']['docroot'] = \wwwroot
DEBUG: default['iis']['log_dir'] = \logs\LogFiles
DEBUG: default['iis']['cache_dir'] = \temp

You can see that only the first attribute is properly calculated be reversing the order of declaration and running again:
`default['iis']['pubroot'] = "#{ENV['SYSTEMDRIVE']}\\inetpub"`
`default['iis']['docroot'] = "#{iis['pubroot']}\\wwwroot"`
`default['iis']['log_dir'] = "#{iis['pubroot']}\\logs\\LogFiles"`
`default['iis']['cache_dir'] = "#{iis['pubroot']}\\temp"`
`default['iis']['home'] = "#{ENV['WINDIR']}\\System32\\inetsrv"`
`default['iis']['conf_dir'] = "#{iis['home']}\\config"`

In this scenario only iis[home] will be empty.

If you fully declare the attributes as below it works in other recipes:
`default['iis']['home'] = "#{ENV['WINDIR']}\\System32\\inetsrv"`
`default['iis']['conf_dir'] = "#{ENV['WINDIR']}\\System32\\inetsrv\\config"`
`default['iis']['pubroot'] = "#{ENV['SYSTEMDRIVE']}\\inetpub"`
`default['iis']['docroot'] = "#{ENV['SYSTEMDRIVE']}\\inetpub\\wwwroot"`
`default['iis']['log_dir'] = "#{ENV['SYSTEMDRIVE']}\\inetpub\\logs\\LogFiles"`
`default['iis']['cache_dir'] = "#{ENV['SYSTEMDRIVE']}\\inetpub\\temp`

**Comment by jtimberman** [comment]
This repository is for the chef-client cookbook maintained by CHEF. I think you probably want to open this issue against https://github.com/chef/chef, yes?
