### ISSUE TITLE
WARNING: Failed to connect to ip-

### ISSUE THREAD

**Issue by hernandezluisbcg** [opscode-cookbooks/chef-client#260]
When I run the following command

knife ssh "role:servers" "touch /home/ubuntu/file.txt"

(output)
WARNING: Failed to connect to ip-172-31-30-34.us-west-2.compute.internal -- SocketError: getaddrinfo: nodename nor servname provided, or not known

WARNING: Failed to connect to ip-172-31-43-208.us-west-2.compute.internal -- SocketError: getaddrinfo: nodename nor servname provided, or not known

WARNING: Failed to connect to ip-172-31-36-181.us-west-2.compute.internal -- SocketError: getaddrinfo: nodename nor servname provided, or not known

WARNING: Failed to connect to ip-172-31-1-220.us-west-2.compute.internal -- SocketError: getaddrinfo: nodename nor servname provided, or not known

I believe the IP addresses for each server is not correct. The IP addresses where auto-detected when I first ran the chef-client. How can I run chef-client and have it detect the correct public IP?

Note, these servers are running on AWS EC2, this shouldn't make a difference but could provide some direction. Thanks :)

**Comment by jtimberman** [comment]
You have opened an issue against the chef-client cookbook. It appears you are reporting a problem in chef-client itself. You should open an issue on https://github.com/chef/chef.
