### ISSUE TITLE
Cookbook doesn't seem to pick up bootstrap'd "environment"

### ISSUE THREAD

**Issue by jfbibeau** [opscode-cookbooks/chef-client#262]
I'm trying to set a client's environment during bootstrap, and when running the chef-client cookbook I would expect to see this environment in the generated /etc/chef/client.rb (similar to how the chef_server_url shows up there). Furthermore the README says this should be the recommended way of setting the environment:
```
node['chef_client']['environment'] - Set the node's environment directly (e.g., knife bootstrap -E), as it makes it easier to move nodes to different environments.
```

However looking at this cookbook's default attributes, it doesn't seem to pick up environment:

```
# We only set these by default because this is what comes from `knife
# bootstrap` (the best way to install Chef Client on managed nodes).
#
# Users can add other configuration options through attributes in
# their favorite way (role, 'site' cookbooks, etc).
default['chef_client']['config'] = {
  'chef_server_url' => Chef::Config[:chef_server_url],
  'validation_client_name' => Chef::Config[:validation_client_name],
  'node_name' => Chef::Config[:node_name] == node['fqdn'] ? false : Chef::Config[:node_name]
}

if Chef::Config.has_key?(:client_fork)
  default['chef_client']['config']['client_fork'] = true
end
```

Wouldn't it make sense to add "environment" under the default['chef_client']['config'] so it picks it up from bootstrap? Right now I'm stuck having to populate it with my wrapper cookbook around chef_client, which makes moving to another environment difficult... 

Thanks!

**Comment by juliandunn** [comment]
The docs are probably subtly wrong. You would set `node['chef_client']['config']['environment']`. Can you test that and see if the README just needs to be updated?

**Comment by jfbibeau** [comment]
Hey,

Sorry maybe I wasn't clear :)

Setting node['chef_client']['config']['environment'] in a wrapper cookbook does end up populating the client.rb file, yes.

However the README seems to imply that node['chef_client']['environment'] is deprecated, because the chef-client cookbook is supposed to automatically pick up the running environment.

For example, when I bootstrap my node and give it a server URL, that server URL automatically ends up in my client.rb. I don't need to explicitly set node['chef_client']['config']['chef_server_url']. 

Similarly, my node is bootstrap'd with an environment name already given - why can't client.rb automatically be populated with it? That way I don't have to specify the environment twice - once during bootstrap and once in my wrapper cookbook. I thought that's what the README implied :)

What I will do tomorrow is test changing the chef-client cookbook and adding the line:

```
'environment' => Chef::Config[:environment],
```

and see if the environment does get populated automatically. Either that line is missing, or I completely misinterpreted the README and you can ignore me :)

**Comment by juliandunn** [comment]
You're probably looking for `node.chef_environment`.

**Comment by jfbibeau** [comment]
Got it working with
```
  'environment' => Chef::Config[:environment] == '_default' ? false : Chef::Config[:environment],
```
And modifying the client.rb template to only include environment if not false. I re-used the same logic as the node_name.

Would you accept a pull request fixing this?

**Comment by juliandunn** [comment]
Yes, but you shouldn't need to modify the `client.rb` template if you just leave the value as `nil` instead of `false`.

**Comment by jfbibeau** [comment]
I tested that and unfortunately it still inserts "environment nil" in the
client.rb file.

JF

**Comment by juliandunn** [comment]
Ah yeah, it's probably because [this](https://github.com/opscode-cookbooks/chef-client/blob/master/templates/default/client.rb.erb#L11) should really get replaced with something like

`@chef_config.sort.select {|k,v| !v.nil? }.each do |option, value|`

and then refactoring to deal with the value inline... but that's beyond the scope of what you're asking :grin: 

So go ahead and submit the PR as-is.
