### ISSUE TITLE
metadata.rb file missing from chef-client-4.2.0.tar.gz

### ISSUE THREAD

**Issue by jfbibeau** [opscode-cookbooks/chef-client#265]
Hey,

So I'm trying to upgrade chef-client cookbook within my repo from 4.0.0 to 4.2.0, but the process keeps failing with:
```
Cookbook chef-client version 4.2.0 successfully installed
ERROR: IOError: Cannot open or read /home/jbibeau/chef-repo/cookbooks/chef-client/metadata.rb!
```
Looking at the fast forward merge that takes place, the metadata.rb file clearly gets deleted
```
Checking out the master branch.
Updating f3215c2..be2a18f
Fast-forward
...
 cookbooks/chef-client/metadata.rb                                                    | 35 -----------------------------------
...
```
I then tried to do a `knife cookbook site download chef-client` and looking at the raw .tar.gz, and it is indeed missing the metadata.rb file.

Is this a bug in the release? The file still seems to be present in the repo...
Thanks!

**Comment by juliandunn** [comment]
I use Stove to upload the cookbooks and this is all explained over in https://github.com/sethvargo/stove/pull/59.

New-enough knives know how to deal with cookbooks that only contain compiled metadata.

**Comment by jfbibeau** [comment]
Perfect, good find, you put my Google-fu to shame :)
