### ISSUE TITLE
Need to be able to override client.rb values

### ISSUE THREAD

**Issue by ebrahim-moshaya** [opscode-cookbooks/chef-client#290]
https://tickets.opscode.com/browse/CHEF-4304

Seeing as running chef-client remotely can't override values of 'log_location' and 'loglevel'. there needs to be attributes set for loglevel and log_rotation in order to override them to STDOUT and info for example. running chef client remotely on a windows node that has client.rb log_location set to c:\chef\log\client.log, I don't get the full chef-client output to STDOUT. This is problematic in that I have to manually create a secondary client.rb config file with log_location set to STDOUT and loglevel set to INFO.

**Comment by juliandunn** [comment]
Sure you can. Just set the attributes `['chef_client']['config']['log_location']` and `['chef_client']['config']['loglevel']`. They just aren't set by default.
