### ISSUE TITLE
find_chef_client can't locate Chef 12 chef-client.bat

### ISSUE THREAD

**Issue by docwhat** [opscode-cookbooks/chef-client#292]
I'm guessing from [helpers.rb:112](https://github.com/opscode-cookbooks/chef-client/blob/master/libraries/helpers.rb#L112) that the chef-client executable used to be a `.exe`.  It appears that it is now a `.bat` in 12.0.3 of chef.

This causes 4.2.4 to break with the message `Could not locate the chef-client bin in any known path. Please set the proper path by overriding the node['chef_client']['bin'] attribute.` when using the `task` recipe.

It looks like issue #244 also breaks the task as well?

**Comment by docwhat** [comment]
It appears this worked before because `find_chef_client` wasn't actually used because the default attribute [was correct](https://github.com/opscode-cookbooks/chef-client/commit/83269a1a32828e4aec29d98ceb910f1ff3554dad#diff-25e5d4a4446ae12a0d6f1162b6160375L163).

But commit 83269a1a3 by @someara changed it and broke compatibility with chef versions that still used the `c:\opscode\chef` path.

**Comment by docwhat** [comment]
It looks like the OSX `.plist` and `launchctl` settings also changed, but don't clean up the old stuff either.

May I suggest reverting this and rolling it out for version 5.0.0 with some proper upgrade handling (and testing)?

**Comment by jtimberman** [comment]
Fixed the Windows attribute in fe3b26d.

**Comment by jtimberman** [comment]
I don't think this warrants a major version bump, as this is definitely a bug fix.

**Comment by mrmarbury** [comment]
This is broken again with at least the chef gem Versions 12.8.1 and 12.9.41 on Windows. Please see my referenced issue above as well.  This can be reproduced an my and my colleagues Windows 8 environment.
