### ISSUE TITLE
CHANGELOG has merge text in it

### ISSUE THREAD

**Issue by docwhat** [opscode-cookbooks/chef-client#293]
Version 4.2.4 of the cookbook's CHANGELOG has a merge line in it: `>>>>>>> 029f756152c4dc97aaf6468b3e44b5ec2284cf61`.

It appears it was due to commit d3c961c made by @someara: [link](https://github.com/opscode-cookbooks/chef-client/commit/d3c961c7731d1f52cc2a28e90868a831514762da#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR39)

**Comment by jtimberman** [comment]
Fixed. Thanks! 76ed527
