### ISSUE TITLE
Setting ssl_verify_mode

### ISSUE THREAD

**Issue by houghtp** [opscode-cookbooks/chef-client#302]
Hi,

Pretty new to chef and i want to disable SSL for our test environment, but can't for the life of me figure out how to do it via the chef-client cookbook. 

I understand i need to set ssl_verify_mode     = 'verify_none' somewhere. I've tried putting it in the config.rb and also in default.rb.

could someone advise please?

thanks

**Comment by juliandunn** [comment]
You want to set the attribute `['chef_client']['config']['ssl_verify_mode']`.
