### ISSUE TITLE
log_location gets wrapped in single and double quotes unless overridden

### ISSUE THREAD

**Issue by wilb** [opscode-cookbooks/chef-client#321]
I've not signed the contribution agreement yet so haven't raised PR, but I've just encountered my client.rb ending up with a line like (note the single and double quotes wrapping it) after upgrading my chef-client cookbook to the latest from master:

`log_location "'/var/log/chef/client.log'"`

I believe this to be as a result of line 32 of recipes/config.rb

`node.default['chef_client']['config']['log_location'] = "'#{log_path}'"`

I've had to override the attribute otherwise chef-client bails as a result of the invalid syntax.

**Comment by alexpop** [comment]
Thanks for reporting the issue.

This new commit: https://github.com/opscode-cookbooks/chef-client/commit/82f6b512094f70bc7ecfabf43274d4049b1c52cf
combined with: https://github.com/opscode-cookbooks/chef-client/blob/master/recipes/config.rb#L32

generate the double quote in client.rb
